name: 'CMake'
description: 'Run CMake'
inputs:
  distro:
    description: 'Distro to run on'
    required: true
    default: 'latest'
  minimal:
    description: 'If minimal'
    required: false
outputs:
  cmake_args:
    description: 'CMake args to use'
runs:
  using: 'docker'
  image: 'docker://votca/buildenv:latest'
  entrypoint: 'entrypoint.sh'
  args:
    - DISTRO=${{ inputs.distro }}
    - MINIMAL=${{ inputs.minimal }}
