name: PR
on:
  create

jobs:
  PR:
    name: Create
    if: ${{ github.event.ref == 'update_master_submodules' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine base branch
        id: base
        run:
          echo "::set-output name=branch::$(echo ${{ github.event.ref }} | sed 's/update_\(.*\)_submodules/\1/')"
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.ref }}
          fetch-depth: 0
      - name: Try to merge master
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git merge origin/${{ steps.base.outputs.branch }} || true
          git push || true
      - name: Create Pull Request
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.create({
              owner: 'junghans',
              repo: 'test-actions',
              title: 'Update ${{ steps.base.outputs.branch }} submodules',
              head: '${{ github.event.ref }}',
              base: 'steps.base.outputs.branch }}'
            })
