on:
  create

jobs:
  PR:
    name: Create
    if: ${{ github.event.ref == 'update_master_submodules' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.ref }}
          fetch-depth: 0
      - name: Try to merge master
        run: |
          git merge origin/master || true
          git push || true
      - name: Create Pull Request
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.create({
              owner: 'junghans',
              repo: 'test-actions',
              title: 'Update master submodules',
              head: '${{ github.event.ref }}',
              base: 'master'
            })
